<?php
/**
 * C3 Media Ltd
 *
 * @title 		Environment Banner.
 * @category	C3
 * @package 	C3_EnvironmentBanner
 * @author		C3 Development Team <development@c3media.co.uk>
 * @copyright   Copyright (c) 2014 C3 Media Ltd (http://www.c3media.co.uk)
 */

/** @var C3_EnvironmentBanner_Helper_Data $helper */
$helper = $this->_helper;



if ($helper->isDisplayFrontendBanner()):
    $env = $helper->getEnvironment();
    $cols = $helper->getEnvColours();
    ?>
    <style type="text/css">





        .ribbon-wrapper {
            width: 160px;
            height: 160px;
            overflow: hidden;
            position: fixed;
            top: 0px;
            right: 0px;
            z-index: 10000;
        }

        .ribbon-inner {
            font: bold 18px Sans-Serif;
            color: rgba(255,255,255,0.5);
            text-align: center;
            text-shadow:     #333 0px 1px 0px;
            -webkit-transform: rotate(45deg);
            -moz-transform: rotate(45deg);
            -ms-transform: rotate(45deg);
            -o-transform: rotate(45deg);
            position: relative;
            padding: 20px 0px;
            left: 3px;
            top: 22px;
            width: 210px;
            opacity: 0.9;
        }
        .ribbon-inner.<?php echo $env ?> {
            background-color: <?php echo $cols->getFeColor() ?>;
            color: <?php echo $cols->getFeBgColor() ?>;
        }





        .ebborder {
            position:fixed;
            z-index: 10000;
        }
        #ebtop,#ebbottom {
            left:0;
            width:100%;
            height:3px;
        }
        #ebtop {
            top:0;
        }
        #ebbottom {
            bottom:0;
        }
        #ebleft,#ebright {
            top:0;
            height:100%;
            width:3px;
        }
        #ebleft {
            left:0;
        }
        #ebright {
            right:0;
        }

        .ebborder {
            background-color: <?php echo $cols->getFeColor() ?>;
        }



        @media all and (max-width: 768px) {
            .ribbon-inner {

                display:none;
            }

            .ribbon-inner {

                display:none;
            }


        }

    </style>
    <div class="ribbon-wrapper" onclick="document.getElementById('envbanner').style.display = 'none';
                                     document.getElementById('ebtop').style.display = 'none';
                                     document.getElementById('ebbottom').style.display = 'none';
                                     document.getElementById('ebleft').style.display = 'none';
                                     document.getElementById('ebright').style.display = 'none';
                                     " id="envbanner"><div class="ribbon-inner <?php echo $env ?>" title="click to hide"><?= $env ? ucfirst($env) : ''; ?></div></div>



    <div id="ebtop" class="ebborder"></div>
    <div id="ebbottom" class="ebborder"></div>
    <div id="ebleft" class="ebborder"></div>
    <div id="ebright" class="ebborder"></div>



<?php endif; ?>